### ISSUE TITLE
Composer can't update  omnipay/targetpay (v2.2.0) (404 not found)

### ISSUE THREAD

**Issue by AMAFsoft** [thephpleague/omnipay-targetpay#4]
Hi ,

When updating composer : i get this erro : 

<pre>
<p>
Updating dependencies (including require-dev)
  - Installing omnipay/targetpay (v2.2.0)
    Downloading: connection...    Failed to download omnipay/targetpay from dist: The "https://api.github.com/repos/omni
pay/targetpay/zipball/7274721c97f6f8ad3d2a8b4dea474ac548c45bac" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing omnipay/targetpay (v2.2.0)
    Cloning 7274721c97f6f8ad3d2a8b4dea474ac548c45bac

  [RuntimeException]
  Failed to clone git@github.com:omnipay/targetpay.git, git was not found, check that it is installed and in your PAT
  H env.
  'git' n?est pas reconnu en tant que commande interne
  ou externe, un programme exécutable ou un fichier de commandes.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers]
 [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platfor
m-reqs] [packages1] ... [packagesN]
</p>
</pre>

Any advice please?

**Comment by googoole** [comment]
i have same error

**Comment by greydnls** [comment]
I just tagged a new release. It should work now. @googoole
